// HUBUNGI DEVALDI AKBAR SURYADI UNTUK KODESUMBER BACKEND
// DID YOU NEED BACKEND CODE? WHATSAPP ME IN BELOW
// WHATSAPP DEVALDI AKBARS +6282143636001

import { Component } from '@angular/core';
import { ServiceService } from '../services/service.service';

@Component({
  selector: 'app-tab2',
  templateUrl: 'tab2.page.html',
  styleUrls: ['tab2.page.scss']
})
export class Tab2Page {

  constructor(private ionicToastService: ServiceService) {}

  hitungSkor() { 
    this.ionicToastService.openToast('NEED BACKEND? WHATSAPP DEVALDI AKBARS +6282143636001');
  }

  //Total awal nilai 126 karena penjabaran indikator jadi akan menambah
  public form = [
    { val: 'SKOR AWAL IBU HAMIL', isChecked: true, value:'2', color:'success', disabled:true, dampak: 'Merupakan kondisi awal Ibu hamil.'},
    { val: 'TERLALU MUDA HAMIL ≤ 16 TH', isChecked: false, value:'4', color:'warning', disabled:false, dampak: 'Rahim dan panggul belum tumbuh mencapai ukuran dewasa, akibatnya diragukan keselamatan dan kesehatan janin dalam kandungan. Mental ibu juga belum cukup dewasa. Bahaya yang mungkin terjadi antara lain bayi lahir belum cukup umur, perdarahan bisa terjadi sebelum bayi lahir, perdarahan dapat terjadi sesudah bayi lahir.'},
    { val: 'TERLALU TUA HAMIL ≤ 35 TH', isChecked: false, value:'4', color:'warning', disabled:false, dampak: 'Pada tubuh ibu terjadi perubahan dari jaringan alat alat kandungan dan jalan lahir oleh karena proses menjadi tua (lebih kaku). Ada kemungkinan lebih besar ibu hamil mendapatkan bayi dengan cacat kelahiran. Pada persalinan dapat terjadi komplikasi (persalinan macet, perdarahan pasca persalinan)'},
    { val: 'TERLALU LAMBAT HAMIL ≥ 4 TH', isChecked: false, value:'4', color:'warning', disabled:false, dampak: 'Ibu hamil pertama dengan lama perkawinan 4 tahun atau lebih. Bahaya yang mungkin terjadi pada primi tua ini antara lain selama hamil dapat timbul masalah, faktor risiko lain karena kehamilannya seperti preeklamsi, dan persalinan tidak lancar.'},
    { val: 'TERLALU LAMA HAMIL ≥ 10 TH', isChecked: false, value:'4', color:'warning', disabled:false, dampak: 'Ibu dalam kehamilan dan persalinan ini seolah-olah mengalami persalinan yang pertama lagi, umur ibu sudah bertambah tua ada kemungkinan timbul penyakit-penyakit pada tubuh ibu hamil atau timbul masalah karena kehamilannya, misalnya kaki bengkak, tekanan darah tinggi, jalan lahir ibu sudah bertambah kaku. Bahaya yang dapat terjadi diantaranya yakni persalinan dapat berjalan tidak lancar, perdarahan pasca persalinan, penyakit ibu hipertensi (tekanan darah tinggi), diabetes, dan lain-lain.'},
    { val: 'TERLALU CEPAT HAMIL ≤ 2 TH', isChecked: false, value:'4', color:'warning', disabled:false, dampak: 'Jarak kehamilan yang paling tepat adalah 2 tahun atau lebih. Jarak kehamilan yang pendek akan mengakibatkan belum pulihnya kondisi tubuh ibu setelah melahirkan, sehingga meningkatkan risiko kelemahan dan kematian ibu. Selain itu ada kemungkinan ibu masih menyusui dimana anak masih butuh asuhan dan perhatian orang tuanya.'},
    { val: 'TERLALU BANYAK ANAK ≥ 4', isChecked: false, value:'4', color:'warning', disabled:false, dampak: 'Karena ibu sering melahirkan maka kemungkinan akan banyak ditemui keadaan seperti kesehatan terganggu dan kekendoran pada dinding rahim. Bahaya yang dapat terjadi yaitu kelainan letak, persalinan letak lintang, robekan rahim pada kelainan letak lintang, persalinan lama, dan perdarahan pasca persalinan. Grande multipara juga bisa menyebabkan solusio plasenta dan plasenta previa.'},
    { val: 'TERLALU TUA UMUR ≥ 35 TH', isChecked: false, value:'4', color:'warning', disabled:false, dampak: 'Ibu hamil berumur 35 tahun atau lebih, dimana pada usia tersebut terjadi perubahan pada jaringan alat-alat kandungan dan jalan lahir tidak lentur lagi. Ada kecenderungan didapatkan penyakit lain dalam tubuh ibu. Bahaya yang dapat terjadi yaitu tekanan darah tinggi dan preeklampsia, ketuban pecah dini, persalinan tidak lancar atau macet, dan perdarahan setelah bayi lahir.'},
    { val: 'TERLALU PENDEK ≥ 145 CM', isChecked: false, value:'4', color:'warning', disabled:false, dampak: 'Wanita hamil yang mempunyai tinggi badan kurang dari 145 cm memiliki resiko tinggi mengalami persalinan secara premature, karena lebih mungkin memiliki panggul yang sempit.'},
    { val: 'PERNAH GAGAL KEHAMILAN', isChecked: false, value:'4', color:'warning', disabled:false, dampak: 'Ada kemungkinan pada kehamilan ini terjadi kegagalan kehamilan lagi, sangat membutuhkan upaya kelangsungan kehamilan dan penyelamatan janin/bayi.'},
    { val: 'PERNAH MELAHIRKAN DENGAN :\nA. TARIKAN TANG / VAKUM', isChecked: false, value:'4', color:'warning', disabled:false, dampak: 'Tindakan dengan cunam/forcep/ vakum dapat menimbulkan robekan jalan lahir, perdarahan pasca persalinan, radang, dan perforasi.'},
    { val: 'B. URI DIROGOH', isChecked: false, value:'4', color:'warning', disabled:false, dampak: 'Riwayat melahirkan dengan uri dirogoh memiliki dampak adanya kejadian berulang pada kehamilan ini, yakni adanya retensio plasenta yang menyebabkan dilakukannya tindakan uri dirogoh.'},
    { val: 'C. DIBERIKAN INFUS / TRANSFUSE', isChecked: false, value:'4', color:'warning', disabled:false, dampak: 'Dikhawatirkan bisa terjadi kejadian berulang yakni adanya perdarahan pp diberi infus pada kehamilan saat ini.'},
    { val: 'PERNAH OPERASI SESAR', isChecked: false, value:'8', color:'danger', disabled:false, dampak: 'Dapat timbul bahaya pada kehamilan bekas seksio sesar seperti terjadi robekan rahim, sangat berbahaya bagi ibu karena pada tempat robekan terjadi perdarahan banyak  kemudian terjadi infeksi dalam rongga perut ibu serta ibu dapat meninggal.'},
    { val: 'PENYAKIT PADA IBU HAMIL :\nA. KURANG DARAH', isChecked: false, value:'4', color:'warning', disabled:false, dampak: 'Pengaruh anemia pada kehamilan yaitu menurunkan daya tahan ibu hamil, sehingga ibu mudah sakit, menghambat pertumbuhan janin, sehingga janin lahir dengan berat badan lahir rendah, dan persalinan prematur. Bahaya yang dapat terjadi bila terjadi anemia berat (Hemoglobin < 6 g%) yaitu kematian janin, persalinan prematur pada kehamilan < 37 minggu, persalinan lama, dan perdarahan pasca persalinan.'},
    { val: 'B. MALARIA', isChecked: false, value:'4', color:'warning', disabled:false, dampak: 'Pengaruh malaria terhadap kehamilan, yang di sebabkan oleh suhu yang tinggi pada waktu serangan, dapat terjadi keguguran atau abortus, kematian janin dalam kandungan, persalinan premature.'},
    { val: 'C. TBC PARU', isChecked: false, value:'4', color:'warning', disabled:false, dampak: 'Penyakit ini tidak secara langsung berpengaruh pada janin. Janin baru akan tertular setelah dilahirkan. Jika tuberkulosis paru berat dapat menurunkan fisik ibu, tenaga, dan air susu ibu (ASI) ikut berkurang. Bahaya yang dapat terjadi yaitu keguguran, bayi lahir belum cukup umur, dan janin mati dalam kandungan.'},
    { val: 'D. PAYAH JANTUNG', isChecked: false, value:'4', color:'warning', disabled:false, dampak: 'Bahaya yang dapat terjadi yaitu payah jantung bertambah berat dan kelahiran prematur. Bahaya yang terjadi dalam persalinan yaitu Berat Badan Lahir Rendah (BBLR) dan bayi dapat lahir mati. Penyakit jantung memberi pengaruh tidak baik kepada kehamilan dan janin dalam kandungan. Apabila ibu menderita hipoksia dan sianosis, hasil konsepsi dapat menderita pula dan mati, yang kemudian disusul oleh abortus.'},
    { val: 'KENCING MANIS (DIABETES)', isChecked: false, value:'4', color:'warning', disabled:false, dampak: 'Bahaya yang dapat terjadi yaitu persalinan prematur, hidramnion, kelainan bawaan, makrosomia, kematian janin dalam kandungan sesudah kehamilan minggu ke-36, dan kematian bayi perinatal (bayi lahir hidup, kemudian mati < 7 hari). Diabetes mempengaruhi timbulnya komplikasi dalam kehamilan seperti preeklampsia, kelainan letak janin, dan insufisiensi plasenta. Diabetes sebagai penyulit yang sering dijumpai dalam persalinan yaitu inersia uteri dan atonia uteri, distosia bahu karena anak besar, lebih sering pengakhiran partus dengan tindakan, termasuk seksio sesarea, lebih mudah terjadi infeksi, dan angka kematian maternal lebih tinggi. Diabetes lebih sering mengakibatkan infeksi nifas dan sepsis, serta menghambat penyembuhan luka jalan lahir, baik ruptur perineum maupun luka episiotomi.'},
    { val: 'PENYAKIT MENULAR SEKSUAL', isChecked: false, value:'4', color:'warning', disabled:false, dampak: 'HIV adalah penyait menular seksual yang dapat ditularkan melalui hubungan seks, transfusi darah, jarum suntik yang terkontaminasi, penularan dari ibu ke janin melalui plasenta selama kehamilan atau saat persalinan. Bahaya yang dapat terjadi antara lain ibu mudah sekali terkena infeksi, pertumbuhan janin intra uterin terhambat dan berat badan lahir rendah, serta peningkatan kelahiran premature. Jika seorang ibu hamil atau pasangannya dicurigai memiliki risiko menderita HIV atau AIDS maka harus dilakukan penapisan terhadap kedua penyakit tersebut melalui pemeriksaan darah. Wanita hamil yang menderita HIV atau AIDS akan ditangani secara khusus di rumah sakit rujukan.'},
    { val: 'BENGKAK PADA MUKA / TUNGKAI\n& TEKANAN DARAH TINGGI', isChecked: false, value:'4', color:'warning', disabled:false, dampak: 'Bengkak pada muka, tangan disertai dengan naiknya tekanan darah sedikit, berarti ada preeklampsia ringan. Bahaya bagi janin dan ibu yaitu menyebabkan gangguan pertumbuhan janin, dan janin mati dalam kandungan.'},
    { val: 'HAMIL KEMBAR ≥ 2', isChecked: false, value:'4', color:'warning', disabled:false, dampak: 'Rahim ibu membesar dan menekan organ dalam dan menyebabkan keluhan-keluhan seperti sesak napas, edema kedua bibir kemaluan dan tungkai, varises, dan hemorrhoid. Bahaya yang dapat terjadi yaitu keracunan kehamilan, hidramnion, anemia, persalinan prematur, kelainan letak, persalinan sukar, dan perdarahan saat persalinan. Pengaruh terhadap ibu yaitu kebutuhan akan zat-zat bertambah, sehingga dapat menyebabkan anemia dan defisiensi zat-zat lainnya, kemungkinan terjadinya hidramnion bertambah 10 kali lebih besar, frekuensi preeklampsia dan eklamsia lebih sering karena uterus yang besar, ibu mengeluh sesak napas, sering miksi, serta terdapat edema dan varises pada tungkai dan vulva. Dapat pula terjadi inersia uteri, perdarahan pasca persalinan, dan solusio plasenta sesudah anak pertama lahir.'},
    { val: 'HAMIL KEMBAR AIR (HYDRAMNION)', isChecked: false, value:'4', color:'warning', disabled:false, dampak: 'Bahaya pada kehamilan yakni: keracunan kehamilan (pre eklamsi / eklamsi), cacat bawaan pada bayi/bayi kecil, kelainan letak (letak sungsang/letak lintang). Bahaya pada persalinan: Persalinan prematur (kurang bulan), berat lahir kurang dari 2500 gram, setelah ketuban pecah dapat terjadi tali pusat membumbung dan perdarahan pasca persalinan.'},
    { val: 'BAYI MATI DALAM KANDUNGAN', isChecked: false, value:'4', color:'warning', disabled:false, dampak: 'Bahaya yang ditimbulkan janin mati dalam kandungan lebih dari 4(empat) minggu adalah timbulnya gangguan pembekuan darah ibu, disebabkan zat-zat berasal dari jaringan mati dari buah kehamilan yang masuk dalam peredaran darah ibu.'},
    { val: 'KEHAMILAN ≥ 1 BULAN', isChecked: false, value:'4', color:'warning', disabled:false, dampak: 'Fungsi dari jaringan uri dan pembuluh darah menurun. Dampak tidak baik bagi janin yaitu janin mengecil, kulit janin mengkerut, lahir dengan berat badan rendah, dan janin dalam rahim dapat mati mendadak. Kehamilan lewat bulan dapat juga menyebabkan risiko pada ibu, seperti distosia karena aksi uterus tidak terkoordinir, janin besar, dan moulding (moulase) kepala kurang sehingga sering dijumpai partus lama, kesalahan letak, inersia uteri, distosia bahu, dan perdarahan pasca persalinan.'},
    { val: 'LETAK SUNGSANG', isChecked: false, value:'8', color:'danger', disabled:false, dampak: 'Letak sungsang adalah kehamilan tua (hamil 8-9 bulan), letak janin dalam rahim dengan kepala diatas dan bokong atau kaki dibawah. Bahaya yang dapat terjadi yaitu bayi lahir dengan gawat napas yang berat dan bayi dapat mati.'},
    { val: 'LETAK LINTANG', isChecked: false, value:'8', color:'danger', disabled:false, dampak: 'Kelainan letak janin di dalam rahim pada kehamilan tua (hamil 8-9 bulan), kepala ada di samping kanan atau kiri dalam rahim ibu. Bayi letak lintang tidak dapat lahir melalui jalan lahir biasa, karena sumbu tubuh janin melintang terhadap sumbu tubuh ibu. Janin letak lintang yang baru mati dalam proses persalinan, dapat dilahirkan dengan alat melalui jalan lahir biasa. Janin kecil dan sudah beberapa waktu mati masih ada kemungkinan dapat lahir secara biasa tanpa bantuan alat. Bahaya yang dapat terjadi pada kelainan letak lintang yaitu pada persalinan yang tidak ditangani dengan benar, dapat terjadi robekan rahim. Akibatnya adalah perdarahan yang mengakibatkan anemia berat, infeksi, ibu syok dan dapat menyebabkan kematian ibu dan janin.'},
    { val: 'PENDARAHAN DALAM KEHAMILAN', isChecked: false, value:'8', color:'danger', disabled:false, dampak: 'Dapat membahayakan ibu menjadi kurang darah, shock dan ibu meninggal, Dapat membahayakan janinnya yaitu bayi mati dalam kandungan, Tindakan operasi sesar terpaksa di lahirkan walaupun kehamilan belum cukup dalam upaya penyelamatan ibu dan bayi, bayi lebih prematur.'},
    { val: 'PREEKLAMSIA / KEJANG-KEJANG', isChecked: false, value:'8', color:'danger', disabled:false, dampak: 'Preeklampsia berat bila tidak ditangani dengan benar akan terjadi kejang-kejang atau eklamsia. Bahaya yang dapat terjadi yaitu ibu dapat tidak sadar (koma) sampai meninggal. Bahaya bagi janin yaitu ada gangguan pertumbuhan janin dan bayi lahir kecil hingga mati dalam kandungan.'}
  ];
  
}
